### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by johnczito** [JuliaStats/PDMats.jl#108]
If we're not waiting on anything, could I request a new release?

I contributed #103 so that I could address some issues (mentioned [here](https://github.com/JuliaStats/Distributions.jl/pull/917#discussion_r297628281) and [here](https://github.com/JuliaStats/Distributions.jl/issues/939#issuecomment-515930335)) with the matrix-variate distributions in `Distributions.jl`.  Once these changes are released I can get that done.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaStats/PDMats.jl/commit/7ce4a5c609b288ab4b0ebaf3c397c9b46f7ce6a2

**Comment by johnczito** [comment]
Thanks!

**Comment by matbesancon** [comment]
@JuliaRegistrator register()
