### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by cscherrer** [JuliaStats/PDMats.jl#110]
Rather than linking to docs, the documentation link currently points to `pkg.julialang.org`. Even stranger, when I search there and eventually find PDMats, I get this:
![git-login](https://user-images.githubusercontent.com/1184449/74164909-3eb11300-4bd9-11ea-9fd8-f3764e155dc1.png)

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaStats/PDMats.jl/commit/2864126daeba02cb57eb5aa565af464d5f0ba111.
