### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [JuliaStats/PDMats.jl#126]
Is it possible to make a new release? I would like to make use of the bugfixes in https://github.com/JuliaStats/PDMats.jl/pull/124.

**Comment by ararslan** [comment]
Just FYI, #119 was merged since the last tag, which warrants a minor version bump, so you'll need to add support for a new version explicitly in any project files.

**Comment by ararslan** [comment]
Done

**Comment by devmotion** [comment]
Great, thank you!
