### ISSUE TITLE
Support for StaticArrays

### ISSUE THREAD

**Issue by btmit** [JuliaStats/PDMats.jl#151]
Are there plans to support `StaticArrays` with `PDMats`?

I'm measuring a 4x speedup on `cholesky()` with a 10x10 `SMatrix` vs `Matrix`, so it seems like this would be worthwhile.

**Comment by devmotion** [comment]
It works but is slightly inconvenient since there is no `PDMat(::AbstractMatrix)` constructor:
```julia
julia> using PDMats, StaticArrays, LinearAlgebra

ulia> S = @SMatrix [1 0;
                     0 1];

julia> A = PDMat(S, cholesky(S))
2×2 PDMat{Float64, SMatrix{2, 2, Float64, 4}}:
 1.0  0.0
 0.0  1.0

julia> A.mat
2×2 SMatrix{2, 2, Float64, 4} with indices SOneTo(2)×SOneTo(2):
 1.0  0.0
 0.0  1.0

julia> A.dim
2

julia> A.chol
Cholesky{Float64, SMatrix{2, 2, Float64, 4}}
U factor:
2×2 UpperTriangular{Float64, SMatrix{2, 2, Float64, 4}}:
 1.0  0.0
  ⋅   1.0
```

**Comment by btmit** [comment]
That's great. I'm really interested in accessing this through the `MvNormal` type so I've created an issue there too

https://github.com/JuliaStats/Distributions.jl/issues/1495#issue-1115204283

**Comment by btmit** [comment]
Are there any plans to support `PDMat(::AbstractMatrix)`?

**Comment by devmotion** [comment]
Yes, it's fixed by https://github.com/JuliaStats/PDMats.jl/pull/131.
