### ISSUE TITLE
Arithmetic with PDMats and UniformScaling

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/PDMats.jl#20]
The `UniformScaling` type provides a convenient notation for a ScalMat in cases where the dimension can be inferred.  By defining methods like

``` julia
+(a::AbstractPDMat,b::UniformScaling) = a + ScalMat(dim(a), @compat(Float64(b.λ)))
```

a common operation like adding a multiple of the identity can be written more concisely.

I can provide a PR if this seems like a good idea.

**Comment by lindahua** [comment]
@dmbates PR is welcomed.

**Comment by devmotion** [comment]
Seems this issue was fixed by https://github.com/JuliaStats/PDMats.jl/pull/21.
