### ISSUE TITLE
PDMats implementing AbstractArray interface

### ISSUE THREAD

**Issue by KrisDM** [JuliaStats/PDMats.jl#40]
Working with PDMats, it made me wonder why AbstractPDMat doesn't derive from AbstractMatrix? Given the class is immutable, we'd only have to implement getindex and size I think.

**Comment by theogf** [comment]
It's an old issue but any comments on this?

**Comment by davidanthoff** [comment]
@andreasnoack what is your take on this? Worth opening a PR?

**Comment by johnczito** [comment]
Bump. I think this would be helpful.

**Comment by johnczito** [comment]
This would be helpful. I'm currently working on `kron` for PDMats, and this would provide a clean [fallback](https://github.com/JuliaLang/julia/blob/f928246ec3fc5e12ef995388324a8fdcd59cb944/stdlib/LinearAlgebra/src/dense.jl#L384) for any pair of arg types. Then as [you](https://github.com/JuliaStats/PDMats.jl/pull/81#issuecomment-520103299) said, anything else would just be a performance improvement.

**Comment by devmotion** [comment]
Fixed by https://github.com/JuliaStats/PDMats.jl/pull/105.
