### ISSUE TITLE
PDMats not working on Julia 0.4.x compiled without GPL libraries

### ISSUE THREAD

**Issue by maartenheremans** [JuliaStats/PDMats.jl#43]
For licensing issues we run a build of julia excluding GPL libraries. (USE_GPL_LIBS=0)

PDMats seems to be incompatible with this:

```
ERROR: LoadError: LoadError: UndefVarError: CHOLMOD not defined
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
while loading /dynizer/.julia_pkg/v0.4/PDMats/src/chol.jl, in expression starting on line 16
while loading /dynizer/.julia_pkg/v0.4/PDMats/src/PDMats.jl, in expression starting on line 50
```

**Comment by andreasnoack** [comment]
You could try to include a conditional statement in `chol.jl` such the definitions using sparse stuff are only defined when the GPL libraries are used. It would be great if you could open a PR if it works.
