### ISSUE TITLE
Looser typing for utility functions

### ISSUE THREAD

**Issue by jmxpearson** [JuliaStats/PDMats.jl#44]
Ran into this while looking at autodiff for the `MvNormal` pdf, which calls `sqmahal`, which calls `quad`, which doesn't accept an array and vector with different eltypes.

I would propose replacing type signatures in `utils.jl` like

```julia
_addscal!{T<:Real}(r::Matrix{T}, a::Matrix{T}, b::Union{Matrix{T}, SparseMatrixCSC{T}}, c::T)
```

with 

```julia
_addscal!(r::Matrix, a::Matrix, b::Union{Matrix, SparseMatrixCSC}, c::Real)
```

and making sure non-inplace versions in `generics.jl` allocate `eltype(r)` to be `promote_type(eltype(a), eltype(b), eltype(c))` (perhaps with an `@inplace` function?). There's plenty of other code that simply duck-types the storage arrays, assuming their types are wide enough to hold the result of the computation, so this doesn't seem to be entirely out of place, but I wanted to make sure I wasn't missing something performance-critical here. 

Happy to work on this PR, since I have to implement some version of this anyway.

**Comment by andreasnoack** [comment]
Seems like a good idea to me to remove the type parameters whenever they are not needed for correctness or dispatch.

**Comment by jmxpearson** [comment]
Good deal. I'll hope to have a PR soon. I'll appreciate someone else taking
a look then.
