### ISSUE TITLE
det( ) function showing error when computing determinant of a square matrix in julia. 

### ISSUE THREAD

**Issue by rahulmankare** [JuliaStats/PDMats.jl#53]
It shows error in lu.jl file at following line-
function lufact{T}(A::AbstractMatrix{T}, pivot::Union{Type{Val{false}}, Type{Val{true}}})
    **S = typeof(zero(T)/one(T))**
    AA = similar(A, S, size(A))
    copy!(AA, A)
    lufact!(AA, pivot)
end

**It shows following error**
**LoadError: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(!Matched::Type{Base.LibGit2.Oid}) at libgit2\oid.jl:88
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:80
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:120**
  ...
 in **lufact(::Array{Any,2}) at .\linalg\lu.jl:118
 in det(::Array{Any,2}) at .\linalg\generic.jl:578**
 in disp_bwo(::Float64, ::Complex{Float64}) at C:\Users\admin\Desktop\new julia program\runit1.jl:208
 in search_roots(::Float64, ::Array{Float64,1}) at C:\Users\admin\Desktop\new julia program\runit1.jl:316
 in include_string(::String, ::String) at .\loading.jl:441
 in include_string(::Module, ::String, ::String) at C:\Users\admin\.julia\v0.5\CodeTools\src\eval.jl:32
 in (::LastMain.LastMain.Atom.##61#64{String,String})() at C:\Users\admin\.julia\v0.5\Atom\src\eval.jl:81
 in withpath(::LastMain.LastMain.Atom.##61#64{String,String}, ::String) at C:\Users\admin\.julia\v0.5\CodeTools\src\utils.jl:30
 in withpath(::Function, ::String) at C:\Users\admin\.julia\v0.5\Atom\src\eval.jl:46
 in macro expansion at C:\Users\admin\.julia\v0.5\Atom\src\eval.jl:79 [inlined]
 in (::LastMain.LastMain.Atom.##60#63{String,String})() at .\task.jl:60
while loading C:\Users\admin\Desktop\new julia program\runit1.jl, in expression starting on line 389

**Comment by andreasnoack** [comment]
Please provide a small example that can reproduce the error.

**Comment by andreasnoack** [comment]
...and the output from `versioninfo()`.

**Comment by rahulmankare** [comment]
suppose I have a matrix with elements 
![image](https://cloud.githubusercontent.com/assets/24428339/21515259/fd6be058-ccf3-11e6-9c15-04dc63c3310f.png)
and now I want determinant of this matix, then when I used det(matrix) it shows error that 

MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(!Matched::Type{Base.LibGit2.Oid}) at libgit2\oid.jl:88
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuildItem}) at pkg/resolve/versionweight.jl:80
  zero(!Matched::Type{Base.Pkg.Resolve.VersionWeights.VWPreBuild}) at pkg/resolve/versionweight.jl:120
  ...
 in lufact(::Array{Any,2}) at .\linalg\lu.jl:118
 in det(::Array{Any,2}) at .\linalg\generic.jl:578
 in include_string(::String, ::String) at .\loading.jl:441
 in eval(::Module, ::Any) at .\boot.jl:234
 in (::LastMain.LastMain.Atom.##67#70)() at C:\Users\admin\.julia\v0.5\Atom\src\eval.jl:40
 in withpath(::LastMain.LastMain.Atom.##67#70, ::Void) at C:\Users\admin\.julia\v0.5

**Comment by rahulmankare** [comment]
versioninfo( )

Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

**Comment by ararslan** [comment]
Looks like your matrix has an `eltype` of `Any` rather than the expected `Complex{Float32}`. If `X` is your matrix, try `det(Complex{Float32}.(X))`.

**Comment by rahulmankare** [comment]
Its not working

shows error that:

MethodError: Cannot `convert` an object of type SubString{String} to an object of type Complex{Float32}
This may have arisen from a call to the constructor Complex{Float32}(...),
since type constructors fall back to convert methods.
 in macro expansion at .\broadcast.jl:129 [inlined]
 in macro expansion at .\simdloop.jl:73 [inlined]
 in macro expansion at .\broadcast.jl:123 [inlined]
 in _broadcast!(::Type{Complex{Float32}}, ::Array{Complex{Float32},2}, ::Tuple{Tuple{Bool,Bool}}, ::Tuple{Tuple{Int64,Int64}}, ::Tuple{Array{Any,2}}, ::Type{Val{1}}) at .\broadcast.jl:117
 in broadcast!(::Type{T}, ::Array{Complex{Float32},2}, ::Array{Any,2}) at .\broadcast.jl:172
 in broadcast_t(::Type{T}, ::Type{T}, ::Array{Any,2}, ::Vararg{Array{Any,2},N}) at .\broadcast.jl:228
 in broadcast(::Type{T}, ::Array{Any,2}) at .\broadcast.jl:230
 in include_string(::String, ::String) at .\loading.jl:441
 in eval(::Module, ::Any) at .\boot.jl:234
 in (::LastMain.LastMain.Atom.##67#70)() at C:\Users\admin\.julia\v0.5\Atom\src\eval.jl:40

**Comment by ararslan** [comment]
Sounds like there's something weird with the types in the matrix; clearly they aren't all numeric. How was the matrix constructed?

**Comment by ararslan** [comment]
I had forgotten to mention: Clearly this is not an issue with this package but with the specific matrix you're using. Thanks Simon for closing.
