### ISSUE TITLE
PDMats on FreeBSD 11, julia 0.5.0

### ISSUE THREAD

**Issue by deyandyankov** [JuliaStats/PDMats.jl#58]
I installed a fresh julia 0.5.0 from FreeBSD ports. The default configuration compiles `julia` with `USE_GPL_LIBS=0`.

I then remove `~/.julia` to start fresh:
```
[azo@euler ~]$ rm -rf .julia
[azo@euler ~]$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  amd64-unknown-freebsd11.0

julia> Pkg.status()
INFO: Initializing package repository /home/azo/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
No packages installed

julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: FreeBSD (amd64-unknown-freebsd11.0)
  CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_AFFINITY NEHALEM)
  LAPACK: libopenblas
  LIBM: libm
  LLVM: libLLVM-3.8.1 (ORCJIT, skylake)

julia>
```

At this point I am able to install `PDMats` but cannot do `using PDMats`:
```
julia> Pkg.add("PDMats")
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of PDMats from https://github.com/JuliaStats/PDMats.jl.git
INFO: Installing Compat v0.13.0
INFO: Installing PDMats v0.5.4
INFO: Package database updated

julia> using PDMats
INFO: Precompiling module PDMats.
ERROR: LoadError: LoadError: UndefVarError: CHOLMOD not defined
 in _init at /usr/local/lib/julia/sys.so:? (repeats 4 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in _init at /usr/local/lib/julia/sys.so:? (repeats 5 times)
while loading /home/azo/.julia/v0.5/PDMats/src/chol.jl, in expression starting on line 7
while loading /home/azo/.julia/v0.5/PDMats/src/PDMats.jl, in expression starting on line 50
ERROR: Failed to precompile PDMats to /home/azo/.julia/lib/v0.5/PDMats.ji.
 in _init at /usr/local/lib/julia/sys.so:? (repeats 5 times)
 in eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:64
 in macro expansion at ./REPL.jl:95 [inlined]
 in (::Base.REPL.##3#4{Base.REPL.REPLBackend})() at ./event.jl:68
```

From looking at `chol.jl` it seems that with julia v0.5.0 we should be using:
```
typealias CholTypeSparse{T} SparseArrays.CHOLMOD.Factor{T}
```

... but having compiled `julia` without `USE_GPL_LIBS=1` I haven't got `CHOLMOD` in `SparseArrays`.
I tried using `Base.LinAlg.CHOLMOD.CholmodFactor{T}` instead but I realised I also don't have `Base.LinAlg.CHOLMOD`.

Therefore I decided to recompile julia with `USE_GPL_LIBS=1`. This compiled SparseArrays and included the necessary julia code and I could successfully install `PDMats` and do `using PDMats`

However, this time there were warnings when I started julia:
```
[azo@euler ~]$ rm -rf .julia
[azo@euler ~]$ julia
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
/usr/local/lib/libcholmod.so.1: Undefined symbol "colamd_printf"")
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  amd64-unknown-freebsd11.0

julia> Pkg.add("PDMats")
INFO: Initializing package repository /home/azo/.julia/v0.5
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of PDMats from https://github.com/JuliaStats/PDMats.jl.git
INFO: Installing Compat v0.13.0
INFO: Installing PDMats v0.5.4
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
/usr/local/lib/libcholmod.so.1: Undefined symbol "colamd_printf"")
INFO: Package database updated

julia> using PDMats
INFO: Precompiling module PDMats.
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
/usr/local/lib/libcholmod.so.1: Undefined symbol "colamd_printf"")
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
/usr/local/lib/libcholmod.so.1: Undefined symbol "colamd_printf"")

julia>
```

So in essence I think there are two issues:
- isn't PDMats supposed to work with and without cholmod? if yes, why doesn't it work on FreeBSD?
- even with cholmod (USE_GPL_LIBS=1), we are we getting the "could not load library libcholmod" error?

I'm afraid I don't have a solution. `/usr/local/lib/libcholmod.so.1` is available on my system but it doesn't seem to have `colamd_printf` in it.

Can someone please look into this?

**Comment by andreasnoack** [comment]
The package assumes that the GPL libraries are installed. There is little incentive change that so this is unlikely to change unless someone volunteers to adjust the code accordingly.

Regarding the second issue: what do you get from `Libdl.dlpath(Libdl.find_library(:libcolamd))`?

**Comment by deyandyankov** [comment]
Thank you for the quick reply.
In this case I think it might be a good idea to come up with a more informative error message instead of `ERROR: LoadError: LoadError: UndefVarError: CHOLMOD not defined`.

Regarding your question on `Libdl.dlpath(Libdl.find_library(:libcolamd))`:
```
[azo@euler ~]$ julia
WARNING: Error during initialization of module CHOLMOD:
ErrorException("could not load library "libcholmod"
/usr/local/lib/libcholmod.so.1: Undefined symbol "colamd_printf"")
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |
|__/                   |  amd64-unknown-freebsd11.0

julia> Libdl.dlpath(Libdl.find_library(:libcolamd))
"/usr/local/bin/../lib/libcolamd.so"

julia>
[azo@euler ~]$ ls -l /usr/local/bin/../lib/libcolamd.so
lrwxr-xr-x  1 root  wheel  14 Jan 23 16:46 /usr/local/bin/../lib/libcolamd.so -> libcolamd.so.1
[azo@euler ~]$ ls -l /usr/local/lib/libcolamd.so
lrwxr-xr-x  1 root  wheel  14 Jan 23 16:46 /usr/local/lib/libcolamd.so -> libcolamd.so.1
[azo@euler ~]$ ls -l /usr/local/lib/libcolamd.so.1
-rw-r--r--  1 root  wheel  29304 Jan 23 16:46 /usr/local/lib/libcolamd.so.1
[azo@euler ~]$
```

happy to provide more information if necessary

**Comment by ararslan** [comment]
I assume you verified with `nm` that the requisite symbol is missing from the library?

**Comment by andreasnoack** [comment]
It looks like Julia picks up the system provided SuiteSparse which might be very old. Can you find out which version? The easiest solution is probably just to build Julia from source. Then we'll pull recent dependencies such that things work and bugs are fixed.

**Comment by ararslan** [comment]
I should note that I personally haven't been entirely successful building Julia from source on FreeBSD, though I haven't tried building from the v0.5.0 source. It may require some trial and error in terms of finding the appropriate Make.user settings.

**Comment by deyandyankov** [comment]
I've got this:
```
[azo@euler ~]$ nm /usr/local/lib/libcolamd.so.1|grep colamd_printf
libcolamd.so.1
[azo@euler ~]$ nm /usr/local/lib/libcolamd.so.1|grep colamd_printf
00000000002068b0 D colamd_printf
[azo@euler ~]$
```

and also I seem to be using `SuiteSparse` 4.0.2_5

**Comment by andreasnoack** [comment]
There seems to be an issue with the Julia build and this doesn't really have anything to do with this package. Could you either try building from source or ask the port maintainer about the SuiteSparse issue?

**Comment by deyandyankov** [comment]
Thanks @andreasnoack, I'll try building from source and will contact the maintainer when I've got more clarity.

**Comment by ararslan** [comment]
Julia 0.5 is no longer supported by this package (nor maintained in general), and Julia should work fine on FreeBSD these days, so I'm going to go ahead and close this.
