### ISSUE TITLE
PDMats broken on Julia v0.7

### ISSUE THREAD

**Issue by oschulz** [JuliaStats/PDMats.jl#68]
PDMats is currently broken on Julia v0.7, since `Base.Test` was removed. This doesn't only affect PDMats testing but PDMats as a whole, as `Base.Test` is used in "src/testutils.jl".

**Comment by oschulz** [comment]
This breaks Travis/Appveyor testing on Julia v0.7 of all packages that require PDMats.

**Comment by ararslan** [comment]
Fixed by #67
