### ISSUE TITLE
Precompilation broken: unknown Base.LAPACK with Julia 0.7

### ISSUE THREAD

**Issue by cynddl** [JuliaStats/PDMats.jl#71]
```Base.LAPACK``` has been removed in Julia 0.7. However, ```Base.LinAlg.LAPACK``` still exists, even if it's deprecated.

The precompilation currently fails as ```Base.LAPACK``` cannot be imported on line 40 of PDMats.jl:

https://github.com/JuliaStats/PDMats.jl/blob/a134789404241f24bcf6eb7a397e8f8591f83705/src/PDMats.jl#L40

I would recommend using ```Base.LinAlg.LAPACK``` instead, which works for Julia < 0.7 and 0.7.

**Comment by ararslan** [comment]
We should use `Compat.LinearAlgebra.LAPACK` for this, and indeed move to `Compat.LinearAlgebra` everywhere here.

This is slightly off topic, but one issue here is that there's no `Compat` support for the `A_mul_B` replacements, so we'll either need to maintain two branches of the code base, one that targets 0.6 and one that targets 0.7, or do as was done in FFTW and drop support for Julia < 0.7. (cc @andreasnoack)

**Comment by andreasnoack** [comment]
Let's do a 0.7 edition and drop support for older versions.

**Comment by dmbates** [comment]
I'm willing to work on creating a version for 0.7

Before I get myself tied up in too many knots, let me describe how I would plan to start and either @andreasnoack or @ararslan can tell me if I am going astray

- create a julia7 branch and check it out
- bump the julia version in the `REQUIRE` file to 0.7.0-
- (at a later date) modify the `METADATA` package to put an upper bound on julia in the `REQUIRE` files for earlier `PDMats` versions
- start going through matrix manipulation (mulitplication, solution of systems) calls and rewrite for the new syntax.
- test, rinse and repeat

Does that sound like a good way to start?

**Comment by ararslan** [comment]
* The version bound in REQUIRE should be more specific, perhaps the version where the linear algebra functionality was moved to the stdlib (`0.7.0-DEV.3449`).

* No need for upper bounding Julia (or really anything in this case) in METADATA, since version resolution will take care of the details.

Other than that, :+1:

**Comment by juliohm** [comment]
@dmbates, thank you for the fixes. How is your plan unrolling? I bumped into this compilation issue today.

**Comment by Nosferican** [comment]
I experimented with bumping a 0.7 version. What is the deal with the `CHOLMOD`? It seems to have been made for supporting Julia 0.4x with non GPL-libraries. Using the nightly it always defaults to `false` so none of that code is included.

**Comment by devmotion** [comment]
I think this is not relevant anymore, we are way beyond Julia 0.7.
