### ISSUE TITLE
Leftover call to `eye()`

### ISSUE THREAD

**Issue by ElOceanografo** [JuliaStats/PDMats.jl#87]
In this line: https://github.com/JuliaStats/PDMats.jl/blob/f1e8246f3bb9cf63f283800c00299957ff8bc219/src/pdsparsemat.jl#L50  Easy fix, just exchange an `eye` for an `I` 😏 

I ran into this issue doing the following:
```julia
using LinearAlgebra
using Distributions
using PDMats

J = sprand(10, 10, 0.05)
J = J'J
J[diagind(J)] .= 1
μ = randn(10)
h = J \ μ
d = MvNormalCanon(μ, h, PDSparseMat(J))
rand(d)
```
N.B., I also don't think sampling from an `MvNormalCanon` should require full inversion of the precision matrix, but that's a separate issue for Distributions.

**Comment by andreasnoack** [comment]
Thanks for reporting this. Would you be able to prepare a PR with the fix?

**Comment by ElOceanografo** [comment]
Sure, though I am now wondering if this should be allowed? `Base.inv` throws an error when you try to use it on a sparse matrix:
```julia
julia> inv(J)
ERROR: The inverse of a sparse matrix can often be dense and can cause the computer to run out of
memory. If you are sure you have enough memory, please convert your matrix to a dense matrix.
```

**Comment by ElOceanografo** [comment]
After some more consideration, I think `inv(a::PDSparseMat{T})` should throw an error for safety/consistency with Base.  Given that the current code already throws an (unintentional) error, this is unlikely to break anything that isn't already broken.  If that sounds good I'll prepare a PR.

**Comment by andreasnoack** [comment]
Fixed by https://github.com/JuliaStats/PDMats.jl/pull/119
