### ISSUE TITLE
Overload LinearAlgebra.cholesky

### ISSUE THREAD

**Issue by oxinabox** [JuliaStats/PDMats.jl#88]
It would be usedful if one could call `cholesky` on a `AbstractPDMat`

For `PDMats` this would just return the precomputed one,
For `DiagPDMats` this would just do the elementwise `sqrt` (right?).

cc @nickrobinson251

**Comment by ararslan** [comment]
For reference, see also https://github.com/JuliaStats/PDMats.jl/pull/81

**Comment by davidanthoff** [comment]
I think this can be closed now?
